### ISSUE TITLE
Can't run VLC

### ISSUE THREAD

**Issue by jaarsolares** [niclabs/BoxingExperience#1]
Hi, my name is Juan and I'm doing my final project to end a telecommunications degree in Spain, the project uses VLC to stream a video between different containers and what I want to do is to measure the quality of the stream in the received video. I found your project very interesting and I wanted to use your VLC version, but when I was trying to compile the VLC I received some errors. First, when I'm using the host and I try to execute the vlc (..vlc$ ./vlc ) I obtain this error "error while loading shared libraries: libvlc.so.5: wrong ELF class: ELFCLASS64".

Plus, if I want to execute the same inside the container it does something different. Executing this command  "sudo -u ubuntu /root/vlc/vlc -vvv /root/video.mp4 --run-time='40' --sout" I get this warning:
"[0x8eda1c0] main libvlc warning: cannot read /home/jcarrera/Documents/vlc/modules/plugins.dat (No such file or directory)". I don't have this directory in my computer so my doubt is if there's a configuration file I have to modify in order to run everything correctly in my computer or if there's another solution to use your VLC. 

Also, when I try to do the configure (./configure) in the vlc folder I get the following message:
"configure: error: cannot find sources (src/libvlc.c) in . or .."

Thanks in advance.
Regards,
Juan.

**Comment by dongraft** [comment]
Hello Juan,
This version of VLC was compiled using a x86 machine. It's requirements might be satisfied by now, but when you try to compile it, it will tell you that it needs specific versions of them (old ones).

Then, we have some options on how to proceed:
- Use the compiled version. As it's compiled using the user jcarrera and it's home directory, you might want to put it on /home/jcarrera/Documents/vlc/ (I think a simple symbolic link or mount point might work, that's why it gives you the second warning you tell us about).
- Try to compile it again, but try not to miss the dependencies. Take a look at https://help.ubuntu.com/community/CompileVLC for more help. Install the required versions of this VLC release. You might want to use the x86 dependencies. export CFLAGS=-m32 could help.
- (WIP, no ETA though) Migrate the changes made to a newer version of VLC that will compile on an x64 environment or simply a newer one.

Please let me know if you have any other questions. 
Jaime (jcarrera)

**Comment by jaarsolares** [comment]
Hello Jaime, thanks for your fast answer. I've put the compiled version in the folder /home/jcarrera/Documents/vlc and now I can run the VLC inside the containers. I can play videos in them using the VLC but what I cannot do a video streaming using them. I even tried the same commands you have in your documents, but there's no traffic going through the network. When I use a no-modified version of the VLC I can do the streaming with no difficulties and I can see the packets going through the tap devices with the wireshark. Do you have any idea about if I'm doing something wrong or a way to make it work?

Thanks beforehand for your collaboration,
Juan.

**Comment by dongraft** [comment]
Let me find you an updated version of our LXC/NS3 configurations and I'll let you know! (I'm a little AFK, but I'll deliver!)

**Comment by jaarsolares** [comment]
Ok, it'd be great, thanks a lot!
Juan.

**Comment by madestro** [comment]
done.
